version: '3.10'

services:
  jupyter:
    image: mixtral_j
    container_name: mixcon
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"  # Port forwarding to access Jupyter Notebook in browser
    volumes:
      - ./notebooks:/home/jovyan/work  # Mount local folder to container
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: >
      jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

volumes:
  notebooks:
    driver: local